### ISSUE TITLE
no data retrieved

### ISSUE THREAD

**Issue by watermanparker** [petergridge/openweathermaphistory#38]
Hi,

I saw similar problem already reported. I am reporting this issue just in case that brings maybe some new info for you on the problem.

Installed version of HA: newest
Installed version of OWMH: newest

HA is not able to receive any data.
I have configured just one sensor - precipitation last 48h (day0rain+day1rain). Sensor shows always 0.0

I have tried steps from [https://github.com/petergridge/openweathermaphistory/issues/36](https://github.com/petergridge/openweathermaphistory/issues/36). Below entry in log. 

2024-06-11 10:02:00.284 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'openweathermaphistory' at custom_components/openweathermaphistory/weatherhistory.py, line 69: with open(file, 'rb') as myfile: (offender: /config/custom_components/openweathermaphistory/weatherhistory.py, line 69: with open(file, 'rb') as myfile:), please create a bug report at https://github.com/petergridge/openweathermaphistory/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/openweathermaphistory/sensor.py", line 110, in _async_update_data
    await self._weather.async_update()
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 254, in async_update
    dailycalls = self.get_stored_data('owm_api_count').get('dailycalls',{})
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 69, in get_stored_data
    with open(file, 'rb') as myfile:

**Comment by petergridge** [comment]
V2.0.14 release, currently Beta for a few weeks for early adopters to verify. This fixes the issue described in the log report
