### ISSUE TITLE
Possible breaking change in 2022.11

### ISSUE THREAD

**Issue by mwhdc** [petergridge/openweathermaphistory#8]
The latest beta is complaining:

```
2022-10-29 08:52:21.449 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.openweathermaphistory.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/openweathermaphistory/sensor.py", line 55, in <module>
    vol.Optional(CONF_UNIT_SYSTEM, default=CONF_UNIT_SYSTEM_METRIC): cv.unit_system,
AttributeError: module 'homeassistant.helpers.config_validation' has no attribute 'unit_system'
2022-10-29 08:52:21.453 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/openweathermaphistory/sensor.py", line 55, in <module>
    vol.Optional(CONF_UNIT_SYSTEM, default=CONF_UNIT_SYSTEM_METRIC): cv.unit_system,
AttributeError: module 'homeassistant.helpers.config_validation' has no attribute 'unit_system'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 865, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 737, in get_platform
    raise ImportError(
ImportError: Exception importing custom_components.openweathermaphistory.sensor
```

**Comment by petergridge** [comment]
Hi I have created V1.0.11 this deprecates the unit_system configuration and replaces it be deriving the unit system from the HA config.

Let me know if this resolves the problem and I will close this defect.

**Comment by mwhdc** [comment]
Working well! Thanks for the quick fix. I use your code to pop an alert when I need to do some manual watering during a run of dry weather. Super useful.

**Comment by petergridge** [comment]
Thanks Michael, It's good to know how people are using the data, glad it is useful
